"""empty message

Revision ID: f420a5586bd3
Revises: b9d1d91d1573
Create Date: 2025-05-23 11:52:27.597023

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f420a5586bd3'
down_revision = 'b9d1d91d1573'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('salt')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('salt', sa.VARCHAR(length=300), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
